### PR TITLE
Bump http-client deps to 0.5.3.2. Bump http-client-tls to 0.3.3

### PR DESCRIPTION
**Pull request by jfischoff**
Remove exported getConnectionWrapper. Rename checkStatus to checkResponse.

### CODE REVIEW

**Comment by alexanderkjeldaas** [comment]
LGTM, but bounds on authenticate-oauth should be raised to 1.6 to work with current stackage nightly.

**Comment by alexanderkjeldaas** [comment]
The branch as-is can't be build with any stackage snapshot.

With a fix to the authenticate-oauth bounds, it still fails:

```
$ stack init
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- wreq.cabal

Selecting the best among 9 snapshots...

* Partially matches lts-7.4
    authenticate-oauth version 1.5.1.2 found
        - wreq requires ==1.6.*
    http-client version 0.4.31.1 found
        - wreq requires >=0.5.3.2
    http-client-tls version 0.2.4.1 found
        - wreq requires >=0.3.3
    Using package flags:
        - wreq: aws = False, developer = False, doctest = True, httpbin = False

* Matches nightly-2016-10-18

Selected resolver: nightly-2016-10-18
Initialising configuration using resolver: nightly-2016-10-18
Total number of user packages considered: 1
Writing configuration to file: stack.yaml
All done.
$ stack build
WARNING: filepath wildcard 'examples/*.cabal' does not match any files.
SHA-1.6.4.2: using precompiled package
base16-bytestring-0.1.1.6: using precompiled package
base-orphans-0.5.4: using precompiled package
base64-bytestring-1.0.0.1: using precompiled package
byteable-0.1.1: using precompiled package
base-compat-0.9.1: using precompiled package
cereal-0.5.3.0: using precompiled package
data-default-class-0.1.2.0: using precompiled package
dlist-0.8.0.2: using precompiled package
entropy-0.3.7: using precompiled package
hourglass-0.2.10: using precompiled package
memory-0.13: using precompiled package
mtl-2.2.1: using precompiled package
network-2.6.3.1: using precompiled package
old-locale-1.0.0.7: using precompiled package
data-default-instances-containers-0.0.1: using precompiled package
data-default-instances-dlist-0.0.1: using precompiled package
parallel-3.2.1.0: using precompiled package
prelude-extras-0.4.0.3: using precompiled package
asn1-types-0.3.2: using precompiled package
cryptonite-0.20: using precompiled package
pem-0.2.2: using precompiled package
data-default-instances-old-locale-0.0.1: using precompiled package
primitive-0.6.1.0: using precompiled package
random-1.1: using precompiled package
reflection-2.1.2: using precompiled package
semigroups-0.18.2: using precompiled package
asn1-encoding-0.9.4: using precompiled package
cryptohash-0.11.9: using precompiled package
socks-0.5.5: using precompiled package
data-default-0.7.1.1: using precompiled package
stm-2.4.4.1: using precompiled package
text-1.2.2.1: using precompiled package
time-locale-compat-0.1.1.3: using precompiled package
transformers-compat-0.5.1.4: using precompiled package
asn1-parse-0.9.4: using precompiled package
crypto-pubkey-types-0.4.3: using precompiled package
vector-0.11.0.0: using precompiled package
zlib-0.6.1.1: using precompiled package
StateVar-1.1.0.4: using precompiled package
async-2.1.0: using precompiled package
blaze-builder-0.4.0.2: using precompiled package
exceptions-0.8.3: using precompiled package
hashable-1.2.4.0: using precompiled package
mime-types-0.1.0.7: using precompiled package
parsec-3.1.11: using precompiled package
tagged-0.8.5: using precompiled package
x509-1.6.4: using precompiled package
cookie-0.4.2.1: using precompiled package
streaming-commons-0.1.16: using precompiled package
case-insensitive-1.2.0.7: using precompiled package
psqueues-0.2.2.2: using precompiled package
scientific-0.3.4.9: using precompiled package
network-uri-2.6.1.0: using precompiled package
crypto-api-0.13.2: using precompiled package
distributive-0.5.0.2: using precompiled package
unordered-containers-0.2.7.1: using precompiled package
void-0.7.1: using precompiled package
http-types-0.9.1: using precompiled package
x509-store-1.6.2: using precompiled package
attoparsec-0.13.1.0: using precompiled package
pureMD5-2.1.3: using precompiled package
contravariant-1.4: using precompiled package
http-client-0.5.3.2: using precompiled package
x509-system-1.6.4: using precompiled package
x509-validation-1.6.5: using precompiled package
aeson-1.0.2.0: using precompiled package
RSA-2.2.0: using precompiled package
comonad-5: using precompiled package
tls-1.3.8: using precompiled package
authenticate-oauth-1.6: using precompiled package
bifunctors-5.4.1: using precompiled package
connection-0.2.6: using precompiled package
profunctors-5.2: using precompiled package
semigroupoids-5.1: using precompiled package
http-client-tls-0.3.3: using precompiled package
free-4.12.4: using precompiled package
adjunctions-4.3: using precompiled package
kan-extensions-5.0.1: using precompiled package
lens-4.14: using precompiled package
lens-aeson-1.0.0.5: using precompiled package
wreq-0.4.1.0: configure
Configuring wreq-0.4.1.0...
wreq-0.4.1.0: build
Preprocessing library wreq-0.4.1.0...
[ 1 of 15] Compiling Network.Wreq.Lens.Machinery ( Network/Wreq/Lens/Machinery.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Lens/Machinery.o )
[ 2 of 15] Compiling Network.Wreq.Internal.OAuth1 ( Network/Wreq/Internal/OAuth1.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Internal/OAuth1.o )
[ 3 of 15] Compiling Network.Wreq.Cache.Store ( Network/Wreq/Cache/Store.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Cache/Store.o )
[ 4 of 15] Compiling Network.Wreq.Internal.Types ( Network/Wreq/Internal/Types.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Internal/Types.o )
[ 5 of 15] Compiling Paths_wreq       ( .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/autogen/Paths_wreq.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Paths_wreq.o )
[ 6 of 15] Compiling Network.Wreq.Internal.Lens ( Network/Wreq/Internal/Lens.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Internal/Lens.o )

/wreq/Network/Wreq/Internal/Lens.hs:45:1: warning: [-Wunused-top-binds]
    Defined but not used: ‘requestManagerOverride’
[ 7 of 15] Compiling Network.Wreq.Internal.AWS ( Network/Wreq/Internal/AWS.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Internal/AWS.o )
[ 8 of 15] Compiling Network.Wreq.Types ( Network/Wreq/Types.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Types.o )
[ 9 of 15] Compiling Network.Wreq.Internal.Link ( Network/Wreq/Internal/Link.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Internal/Link.o )
[10 of 15] Compiling Network.Wreq.Lens.TH ( Network/Wreq/Lens/TH.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Lens/TH.o )
[11 of 15] Compiling Network.Wreq.Lens ( Network/Wreq/Lens.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Lens.o )
[12 of 15] Compiling Network.Wreq.Cache ( Network/Wreq/Cache.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Cache.o )

/wreq/Network/Wreq/Cache.hs:153:30: warning: [-Wdeprecations]
    In the use of ‘parseTime’
    (imported from Data.Time.Format, but defined in time-1.6.0.1:Data.Time.Format.Parse):
    Deprecated: "use "parseTimeM True" instead"
[13 of 15] Compiling Network.Wreq.Internal ( Network/Wreq/Internal.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Network/Wreq/Internal.o )

/wreq/Network/Wreq/Internal.hs:150:33: error:
    • Variable not in scope:
        checkResponse
          :: Options -> Maybe (Request -> Response BodyReader -> IO ())
    • Perhaps you meant one of these:
        ‘HTTP.checkResponse’ (imported from Network.HTTP.Client),
        ‘Lens.checkResponse’ (imported from Network.Wreq.Internal.Lens)
      Perhaps you want to add ‘checkResponse’
      to one of these import lists:
        ‘Network.HTTP.Client’ (Network/Wreq/Internal.hs:30:1-39)
        ‘Network.HTTP.Client.Internal’ (Network/Wreq/Internal.hs:31:1-80)
        ‘Network.Wreq.Internal.Lens’ (Network/Wreq/Internal.hs:33:1-45)
WARNING: filepath wildcard 'examples/*.cabal' does not match any files.
Completed 82 action(s).

--  While building package wreq-0.4.1.0 using:
      /wreq/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build lib:wreq --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
$
```

**Comment by bugthunk** [comment]
Is stack compatibility what's keeping this from being merged? I need to set an upper bound `http-client-tls < 0.3`) in my project for deps to work - such a bound on security related packages sort of hurt, just on mere principle.

**Comment by relrod** [comment]
@bos ping?

**Comment by ondrap** [comment]
I have fixed this here: https://github.com/ondrap/wreq/tree/http-client-bump . I didn't make it pull request as it is a fork of a fork that already has a pull request.

@bos, any way to add somebody as a co-maintainer? There are other packages depending on wreq and it would be nice to have it compile with the newest http-client.

**Comment by joehillen** [comment]
@ondrap Forks of forks is what git is all about. You should open a new PR for your fork since this one doesn't build, and this one should be closed.

**Comment by ondrap** [comment]
Ok, it's here: #94

**Comment by jfischoff** [comment]
Sorry I've to busy to revisit this, thanks for carrying the torch @ondrap

**Comment by joehillen** [comment]
@jfischoff You should close this.

**Pull request closed without merging**
