### PR TITLE
Add support for the HTTP PATCH method

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Add support for the HTTP PATCH method including supporting functions and
unit tests.

### CODE REVIEW

**Comment by Rydgel** [comment]
Digging this. Especially the Network.Wreq.Session module part, since there is no customMethod in it.

**Comment by bos** [comment]
I think this is superseded by #79?

**Comment by Rydgel** [comment]
I think it does :)

**Comment by kellymclaughlin** [comment]
Right, this is probably unnecessary. Closing.

**Pull request closed without merging**
