### PR TITLE
Use `newSession` instead of `withSession` 

### PR DESCRIPTION
**Pull request by jfischoff**
This is in response to issue #81 "It shall be reasonable to add a standalone `newSession` action"

### CODE REVIEW

**Comment by alexanderkjeldaas** [comment]
The `wreq-examples` project fails.  Missing changes:

```
Network/Wreq/Session.hs:-- main = Sess.'withSession' $ \\sess ->
Network/Wreq/Session.hs:-- We create a 'Session' using 'withSession', then pass the session to
changelog.md:* New withAPISession and withSessionControl functions make talking to
examples/SimpleSession.hs:main = S.withSession $ \sess -> do
tests/UnitTests.hs:cookieSession site = Session.withSession $ \s -> do
tests/UnitTests.hs:snapHeadSessionBug site = Session.withSession $ \s -> do
tests/UnitTests.hs:  Session.withSession $ \s ->
www/tutorial.md:main = S.withSession $ \sess -> do
www/tutorial.md:* To create a `Session`, we use `S.withSession`. It calls our code
```

**Comment by bos** [comment]
This breaks the public API unnecessarily. Please add new entrypoints instead of renaming and changing the types of those that already exist.

**Comment by jfischoff** [comment]
@bos roger

**Comment by ondrap** [comment]
Implemented seperately, deprecating the former functions.

**Pull request closed without merging**
